branch-defaults:
  master:
    environment: tikapeForum-env
    group_suffix: null
global:
  application_name: tikape-forum
  default_ec2_keyname: jesse-aws
  default_platform: Ruby 2.3 (Puma)
  default_region: eu-west-1
  profile: eb-cli
  sc: git
