PRAGMA foreign_keys = true;
CREATE TABLE Category (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	subject VARCHAR(255) NOT NULL,
	upper_category_id UNSIGNED INTEGER NOT NULL,
	FOREIGN KEY(upper_category_id) REFERENCES Category(id)
);

CREATE TABLE Discussion (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	title VARCHAR(255) NOT NULL,
	category_id UNSIGNED INTEGER NOT NULL,
	FOREIGN KEY(category_id) REFERENCES Category(id)
);

CREATE TABLE Message (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	user_id VARCHAR(255) NOT NULL,
	message TEXT NOT NULL,
	time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	last_edited TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	discussion_id UNSIGNED INTEGER NOT NULL,
	FOREIGN KEY(discussion_id) REFERENCES Discussion(id)
	FOREIGN KEY(user_id) REFERENCES User(id)
);

CREATE TABLE User (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	nick VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	salt VARCHAR(255) NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	admin boolean DEFAULT False NOT NULL,
	last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);